/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq;


import com.iot.baobiao.jooq.tables.Baobiaoorder;
import com.iot.baobiao.jooq.tables.SelfSite;
import com.iot.baobiao.jooq.tables.Site;
import com.iot.baobiao.jooq.tables.User;
import com.iot.baobiao.jooq.tables.UserSite;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Nutch extends SchemaImpl {

    private static final long serialVersionUID = -716237657;

    /**
     * The reference instance of <code>nutch</code>
     */
    public static final Nutch NUTCH = new Nutch();

    /**
     * The table <code>nutch.baobiaoorder</code>.
     */
    public final Baobiaoorder BAOBIAOORDER = com.iot.baobiao.jooq.tables.Baobiaoorder.BAOBIAOORDER;

    /**
     * The table <code>nutch.self_site</code>.
     */
    public final SelfSite SELF_SITE = com.iot.baobiao.jooq.tables.SelfSite.SELF_SITE;

    /**
     * The table <code>nutch.site</code>.
     */
    public final Site SITE = com.iot.baobiao.jooq.tables.Site.SITE;

    /**
     * The table <code>nutch.user</code>.
     */
    public final User USER = com.iot.baobiao.jooq.tables.User.USER;

    /**
     * The table <code>nutch.user_site</code>.
     */
    public final UserSite USER_SITE = com.iot.baobiao.jooq.tables.UserSite.USER_SITE;

    /**
     * No further instances allowed
     */
    private Nutch() {
        super("nutch", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Baobiaoorder.BAOBIAOORDER,
            SelfSite.SELF_SITE,
            Site.SITE,
            User.USER,
            UserSite.USER_SITE);
    }
}
