/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq;


import com.iot.baobiao.jooq.tables.Baobiaoorder;
import com.iot.baobiao.jooq.tables.SelfSite;
import com.iot.baobiao.jooq.tables.Site;
import com.iot.baobiao.jooq.tables.User;
import com.iot.baobiao.jooq.tables.UserSite;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in nutch
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>nutch.baobiaoorder</code>.
     */
    public static final Baobiaoorder BAOBIAOORDER = com.iot.baobiao.jooq.tables.Baobiaoorder.BAOBIAOORDER;

    /**
     * The table <code>nutch.self_site</code>.
     */
    public static final SelfSite SELF_SITE = com.iot.baobiao.jooq.tables.SelfSite.SELF_SITE;

    /**
     * The table <code>nutch.site</code>.
     */
    public static final Site SITE = com.iot.baobiao.jooq.tables.Site.SITE;

    /**
     * The table <code>nutch.user</code>.
     */
    public static final User USER = com.iot.baobiao.jooq.tables.User.USER;

    /**
     * The table <code>nutch.user_site</code>.
     */
    public static final UserSite USER_SITE = com.iot.baobiao.jooq.tables.UserSite.USER_SITE;
}
