/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.records;


import com.iot.baobiao.jooq.tables.Baobiaoorder;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BaobiaoorderRecord extends UpdatableRecordImpl<BaobiaoorderRecord> implements Record7<Integer, Integer, String, String, Double, Timestamp, Integer> {

    private static final long serialVersionUID = -1929035184;

    /**
     * Setter for <code>nutch.baobiaoorder.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nutch.baobiaoorder.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nutch.baobiaoorder.userid</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>nutch.baobiaoorder.userid</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>nutch.baobiaoorder.outtradeno</code>.
     */
    public void setOuttradeno(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>nutch.baobiaoorder.outtradeno</code>.
     */
    public String getOuttradeno() {
        return (String) get(2);
    }

    /**
     * Setter for <code>nutch.baobiaoorder.tradeno</code>.
     */
    public void setTradeno(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>nutch.baobiaoorder.tradeno</code>.
     */
    public String getTradeno() {
        return (String) get(3);
    }

    /**
     * Setter for <code>nutch.baobiaoorder.amount</code>.
     */
    public void setAmount(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>nutch.baobiaoorder.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>nutch.baobiaoorder.time</code>.
     */
    public void setTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>nutch.baobiaoorder.time</code>.
     */
    public Timestamp getTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>nutch.baobiaoorder.status</code>. 0代表成功支付，1代表等待支付，2代表未付款交易超时关闭，或支付完成后全额退款，3代表未知状态
     */
    public void setStatus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>nutch.baobiaoorder.status</code>. 0代表成功支付，1代表等待支付，2代表未付款交易超时关闭，或支付完成后全额退款，3代表未知状态
     */
    public Integer getStatus() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, Double, Timestamp, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, Double, Timestamp, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Baobiaoorder.BAOBIAOORDER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Baobiaoorder.BAOBIAOORDER.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Baobiaoorder.BAOBIAOORDER.OUTTRADENO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Baobiaoorder.BAOBIAOORDER.TRADENO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Baobiaoorder.BAOBIAOORDER.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Baobiaoorder.BAOBIAOORDER.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Baobiaoorder.BAOBIAOORDER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOuttradeno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTradeno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaobiaoorderRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaobiaoorderRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaobiaoorderRecord value3(String value) {
        setOuttradeno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaobiaoorderRecord value4(String value) {
        setTradeno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaobiaoorderRecord value5(Double value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaobiaoorderRecord value6(Timestamp value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaobiaoorderRecord value7(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BaobiaoorderRecord values(Integer value1, Integer value2, String value3, String value4, Double value5, Timestamp value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BaobiaoorderRecord
     */
    public BaobiaoorderRecord() {
        super(Baobiaoorder.BAOBIAOORDER);
    }

    /**
     * Create a detached, initialised BaobiaoorderRecord
     */
    public BaobiaoorderRecord(Integer id, Integer userid, String outtradeno, String tradeno, Double amount, Timestamp time, Integer status) {
        super(Baobiaoorder.BAOBIAOORDER);

        set(0, id);
        set(1, userid);
        set(2, outtradeno);
        set(3, tradeno);
        set(4, amount);
        set(5, time);
        set(6, status);
    }
}
