/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.records;


import com.iot.baobiao.jooq.tables.SelfSite;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelfSiteRecord extends UpdatableRecordImpl<SelfSiteRecord> implements Record15<Integer, String, String, String, String, Integer, Timestamp, String, String, Timestamp, BigDecimal, String, String, Integer, String> {

    private static final long serialVersionUID = -916458747;

    /**
     * Setter for <code>nutch.self_site.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nutch.self_site.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nutch.self_site.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>nutch.self_site.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>nutch.self_site.code</code>. ʡ
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>nutch.self_site.code</code>. ʡ
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>nutch.self_site.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>nutch.self_site.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>nutch.self_site.category</code>.
     */
    public void setCategory(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>nutch.self_site.category</code>.
     */
    public String getCategory() {
        return (String) get(4);
    }

    /**
     * Setter for <code>nutch.self_site.order_index</code>.
     */
    public void setOrderIndex(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>nutch.self_site.order_index</code>.
     */
    public Integer getOrderIndex() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>nutch.self_site.fetch_time</code>. ץȡʱ
     */
    public void setFetchTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>nutch.self_site.fetch_time</code>. ץȡʱ
     */
    public Timestamp getFetchTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>nutch.self_site.text_value</code>.
     */
    public void setTextValue(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>nutch.self_site.text_value</code>.
     */
    public String getTextValue() {
        return (String) get(7);
    }

    /**
     * Setter for <code>nutch.self_site.html_value</code>.
     */
    public void setHtmlValue(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>nutch.self_site.html_value</code>.
     */
    public String getHtmlValue() {
        return (String) get(8);
    }

    /**
     * Setter for <code>nutch.self_site.date_value</code>.
     */
    public void setDateValue(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>nutch.self_site.date_value</code>.
     */
    public Timestamp getDateValue() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>nutch.self_site.num_value</code>.
     */
    public void setNumValue(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>nutch.self_site.num_value</code>.
     */
    public BigDecimal getNumValue() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>nutch.self_site.server_num</code>.
     */
    public void setServerNum(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>nutch.self_site.server_num</code>.
     */
    public String getServerNum() {
        return (String) get(11);
    }

    /**
     * Setter for <code>nutch.self_site.domain</code>.
     */
    public void setDomain(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>nutch.self_site.domain</code>.
     */
    public String getDomain() {
        return (String) get(12);
    }

    /**
     * Setter for <code>nutch.self_site.url_id</code>.
     */
    public void setUrlId(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>nutch.self_site.url_id</code>.
     */
    public Integer getUrlId() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>nutch.self_site.location</code>.
     */
    public void setLocation(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>nutch.self_site.location</code>.
     */
    public String getLocation() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, String, String, Integer, Timestamp, String, String, Timestamp, BigDecimal, String, String, Integer, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, String, String, Integer, Timestamp, String, String, Timestamp, BigDecimal, String, String, Integer, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SelfSite.SELF_SITE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SelfSite.SELF_SITE.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SelfSite.SELF_SITE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SelfSite.SELF_SITE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SelfSite.SELF_SITE.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SelfSite.SELF_SITE.ORDER_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return SelfSite.SELF_SITE.FETCH_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SelfSite.SELF_SITE.TEXT_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SelfSite.SELF_SITE.HTML_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return SelfSite.SELF_SITE.DATE_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return SelfSite.SELF_SITE.NUM_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return SelfSite.SELF_SITE.SERVER_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return SelfSite.SELF_SITE.DOMAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return SelfSite.SELF_SITE.URL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return SelfSite.SELF_SITE.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getOrderIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getFetchTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTextValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getHtmlValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getDateValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getNumValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getServerNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getDomain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getUrlId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value2(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value3(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value5(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value6(Integer value) {
        setOrderIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value7(Timestamp value) {
        setFetchTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value8(String value) {
        setTextValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value9(String value) {
        setHtmlValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value10(Timestamp value) {
        setDateValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value11(BigDecimal value) {
        setNumValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value12(String value) {
        setServerNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value13(String value) {
        setDomain(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value14(Integer value) {
        setUrlId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord value15(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelfSiteRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, Timestamp value7, String value8, String value9, Timestamp value10, BigDecimal value11, String value12, String value13, Integer value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelfSiteRecord
     */
    public SelfSiteRecord() {
        super(SelfSite.SELF_SITE);
    }

    /**
     * Create a detached, initialised SelfSiteRecord
     */
    public SelfSiteRecord(Integer id, String url, String code, String name, String category, Integer orderIndex, Timestamp fetchTime, String textValue, String htmlValue, Timestamp dateValue, BigDecimal numValue, String serverNum, String domain, Integer urlId, String location) {
        super(SelfSite.SELF_SITE);

        set(0, id);
        set(1, url);
        set(2, code);
        set(3, name);
        set(4, category);
        set(5, orderIndex);
        set(6, fetchTime);
        set(7, textValue);
        set(8, htmlValue);
        set(9, dateValue);
        set(10, numValue);
        set(11, serverNum);
        set(12, domain);
        set(13, urlId);
        set(14, location);
    }
}
