/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.records;


import com.iot.baobiao.jooq.tables.Site;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SiteRecord extends UpdatableRecordImpl<SiteRecord> implements Record5<Integer, String, String, String, Timestamp> {

    private static final long serialVersionUID = -1624911574;

    /**
     * Setter for <code>nutch.site.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nutch.site.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nutch.site.domain</code>.
     */
    public void setDomain(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>nutch.site.domain</code>.
     */
    public String getDomain() {
        return (String) get(1);
    }

    /**
     * Setter for <code>nutch.site.start_url</code>.
     */
    public void setStartUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>nutch.site.start_url</code>.
     */
    public String getStartUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>nutch.site.sitename</code>.
     */
    public void setSitename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>nutch.site.sitename</code>.
     */
    public String getSitename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>nutch.site.fetch_time</code>.
     */
    public void setFetchTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>nutch.site.fetch_time</code>.
     */
    public Timestamp getFetchTime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Site.SITE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Site.SITE.DOMAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Site.SITE.START_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Site.SITE.SITENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Site.SITE.FETCH_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDomain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStartUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSitename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getFetchTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SiteRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SiteRecord value2(String value) {
        setDomain(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SiteRecord value3(String value) {
        setStartUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SiteRecord value4(String value) {
        setSitename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SiteRecord value5(Timestamp value) {
        setFetchTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SiteRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SiteRecord
     */
    public SiteRecord() {
        super(Site.SITE);
    }

    /**
     * Create a detached, initialised SiteRecord
     */
    public SiteRecord(Integer id, String domain, String startUrl, String sitename, Timestamp fetchTime) {
        super(Site.SITE);

        set(0, id);
        set(1, domain);
        set(2, startUrl);
        set(3, sitename);
        set(4, fetchTime);
    }
}
