/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.records;


import com.iot.baobiao.jooq.tables.UserSite;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSiteRecord extends UpdatableRecordImpl<UserSiteRecord> implements Record5<Integer, Integer, Integer, String, String> {

    private static final long serialVersionUID = -812436477;

    /**
     * Setter for <code>nutch.user_site.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>nutch.user_site.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nutch.user_site.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>nutch.user_site.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>nutch.user_site.site_id</code>.
     */
    public void setSiteId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>nutch.user_site.site_id</code>.
     */
    public Integer getSiteId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>nutch.user_site.sitename</code>.
     */
    public void setSitename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>nutch.user_site.sitename</code>.
     */
    public String getSitename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>nutch.user_site.start_url</code>.
     */
    public void setStartUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>nutch.user_site.start_url</code>.
     */
    public String getStartUrl() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserSite.USER_SITE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserSite.USER_SITE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserSite.USER_SITE.SITE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserSite.USER_SITE.SITENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UserSite.USER_SITE.START_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSiteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSitename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStartUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSiteRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSiteRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSiteRecord value3(Integer value) {
        setSiteId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSiteRecord value4(String value) {
        setSitename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSiteRecord value5(String value) {
        setStartUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSiteRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSiteRecord
     */
    public UserSiteRecord() {
        super(UserSite.USER_SITE);
    }

    /**
     * Create a detached, initialised UserSiteRecord
     */
    public UserSiteRecord(Integer id, Integer userId, Integer siteId, String sitename, String startUrl) {
        super(UserSite.USER_SITE);

        set(0, id);
        set(1, userId);
        set(2, siteId);
        set(3, sitename);
        set(4, startUrl);
    }
}
