/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Baobiaoorder implements Serializable {

    private static final long serialVersionUID = -832033392;

    private Integer   id;
    private Integer   userid;
    private String    outtradeno;
    private String    tradeno;
    private Double    amount;
    private Timestamp time;
    private Integer   status;

    public Baobiaoorder() {}

    public Baobiaoorder(Baobiaoorder value) {
        this.id = value.id;
        this.userid = value.userid;
        this.outtradeno = value.outtradeno;
        this.tradeno = value.tradeno;
        this.amount = value.amount;
        this.time = value.time;
        this.status = value.status;
    }

    public Baobiaoorder(
        Integer   id,
        Integer   userid,
        String    outtradeno,
        String    tradeno,
        Double    amount,
        Timestamp time,
        Integer   status
    ) {
        this.id = id;
        this.userid = userid;
        this.outtradeno = outtradeno;
        this.tradeno = tradeno;
        this.amount = amount;
        this.time = time;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getOuttradeno() {
        return this.outtradeno;
    }

    public void setOuttradeno(String outtradeno) {
        this.outtradeno = outtradeno;
    }

    public String getTradeno() {
        return this.tradeno;
    }

    public void setTradeno(String tradeno) {
        this.tradeno = tradeno;
    }

    public Double getAmount() {
        return this.amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Timestamp getTime() {
        return this.time;
    }

    public void setTime(Timestamp time) {
        this.time = time;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Baobiaoorder (");

        sb.append(id);
        sb.append(", ").append(userid);
        sb.append(", ").append(outtradeno);
        sb.append(", ").append(tradeno);
        sb.append(", ").append(amount);
        sb.append(", ").append(time);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
