/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Site implements Serializable {

    private static final long serialVersionUID = -755599863;

    private Integer   id;
    private String    domain;
    private String    startUrl;
    private String    sitename;
    private Timestamp fetchTime;

    public Site() {}

    public Site(Site value) {
        this.id = value.id;
        this.domain = value.domain;
        this.startUrl = value.startUrl;
        this.sitename = value.sitename;
        this.fetchTime = value.fetchTime;
    }

    public Site(
        Integer   id,
        String    domain,
        String    startUrl,
        String    sitename,
        Timestamp fetchTime
    ) {
        this.id = id;
        this.domain = domain;
        this.startUrl = startUrl;
        this.sitename = sitename;
        this.fetchTime = fetchTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDomain() {
        return this.domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    public String getStartUrl() {
        return this.startUrl;
    }

    public void setStartUrl(String startUrl) {
        this.startUrl = startUrl;
    }

    public String getSitename() {
        return this.sitename;
    }

    public void setSitename(String sitename) {
        this.sitename = sitename;
    }

    public Timestamp getFetchTime() {
        return this.fetchTime;
    }

    public void setFetchTime(Timestamp fetchTime) {
        this.fetchTime = fetchTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Site (");

        sb.append(id);
        sb.append(", ").append(domain);
        sb.append(", ").append(startUrl);
        sb.append(", ").append(sitename);
        sb.append(", ").append(fetchTime);

        sb.append(")");
        return sb.toString();
    }
}
