/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSite implements Serializable {

    private static final long serialVersionUID = 2111362238;

    private Integer id;
    private Integer userId;
    private Integer siteId;
    private String  sitename;
    private String  startUrl;

    public UserSite() {}

    public UserSite(UserSite value) {
        this.id = value.id;
        this.userId = value.userId;
        this.siteId = value.siteId;
        this.sitename = value.sitename;
        this.startUrl = value.startUrl;
    }

    public UserSite(
        Integer id,
        Integer userId,
        Integer siteId,
        String  sitename,
        String  startUrl
    ) {
        this.id = id;
        this.userId = userId;
        this.siteId = siteId;
        this.sitename = sitename;
        this.startUrl = startUrl;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getSiteId() {
        return this.siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    public String getSitename() {
        return this.sitename;
    }

    public void setSitename(String sitename) {
        this.sitename = sitename;
    }

    public String getStartUrl() {
        return this.startUrl;
    }

    public void setStartUrl(String startUrl) {
        this.startUrl = startUrl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserSite (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(siteId);
        sb.append(", ").append(sitename);
        sb.append(", ").append(startUrl);

        sb.append(")");
        return sb.toString();
    }
}
