/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.daos;


import com.iot.baobiao.jooq.tables.SelfSite;
import com.iot.baobiao.jooq.tables.records.SelfSiteRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SelfSiteDao extends DAOImpl<SelfSiteRecord, com.iot.baobiao.jooq.tables.pojos.SelfSite, Integer> {

    /**
     * Create a new SelfSiteDao without any configuration
     */
    public SelfSiteDao() {
        super(SelfSite.SELF_SITE, com.iot.baobiao.jooq.tables.pojos.SelfSite.class);
    }

    /**
     * Create a new SelfSiteDao with an attached configuration
     */
    @Autowired
    public SelfSiteDao(Configuration configuration) {
        super(SelfSite.SELF_SITE, com.iot.baobiao.jooq.tables.pojos.SelfSite.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.iot.baobiao.jooq.tables.pojos.SelfSite object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchById(Integer... values) {
        return fetch(SelfSite.SELF_SITE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.iot.baobiao.jooq.tables.pojos.SelfSite fetchOneById(Integer value) {
        return fetchOne(SelfSite.SELF_SITE.ID, value);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByUrl(String... values) {
        return fetch(SelfSite.SELF_SITE.URL, values);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByCode(String... values) {
        return fetch(SelfSite.SELF_SITE.CODE, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByName(String... values) {
        return fetch(SelfSite.SELF_SITE.NAME, values);
    }

    /**
     * Fetch records that have <code>category IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByCategory(String... values) {
        return fetch(SelfSite.SELF_SITE.CATEGORY, values);
    }

    /**
     * Fetch records that have <code>order_index IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByOrderIndex(Integer... values) {
        return fetch(SelfSite.SELF_SITE.ORDER_INDEX, values);
    }

    /**
     * Fetch records that have <code>fetch_time IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByFetchTime(Timestamp... values) {
        return fetch(SelfSite.SELF_SITE.FETCH_TIME, values);
    }

    /**
     * Fetch records that have <code>text_value IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByTextValue(String... values) {
        return fetch(SelfSite.SELF_SITE.TEXT_VALUE, values);
    }

    /**
     * Fetch records that have <code>html_value IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByHtmlValue(String... values) {
        return fetch(SelfSite.SELF_SITE.HTML_VALUE, values);
    }

    /**
     * Fetch records that have <code>date_value IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByDateValue(Timestamp... values) {
        return fetch(SelfSite.SELF_SITE.DATE_VALUE, values);
    }

    /**
     * Fetch records that have <code>num_value IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByNumValue(BigDecimal... values) {
        return fetch(SelfSite.SELF_SITE.NUM_VALUE, values);
    }

    /**
     * Fetch records that have <code>server_num IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByServerNum(String... values) {
        return fetch(SelfSite.SELF_SITE.SERVER_NUM, values);
    }

    /**
     * Fetch records that have <code>domain IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByDomain(String... values) {
        return fetch(SelfSite.SELF_SITE.DOMAIN, values);
    }

    /**
     * Fetch records that have <code>url_id IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByUrlId(Integer... values) {
        return fetch(SelfSite.SELF_SITE.URL_ID, values);
    }

    /**
     * Fetch records that have <code>location IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.SelfSite> fetchByLocation(String... values) {
        return fetch(SelfSite.SELF_SITE.LOCATION, values);
    }
}
