/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.daos;


import com.iot.baobiao.jooq.tables.User;
import com.iot.baobiao.jooq.tables.records.UserRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserDao extends DAOImpl<UserRecord, com.iot.baobiao.jooq.tables.pojos.User, Integer> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, com.iot.baobiao.jooq.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    @Autowired
    public UserDao(Configuration configuration) {
        super(User.USER, com.iot.baobiao.jooq.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.iot.baobiao.jooq.tables.pojos.User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.User> fetchById(Integer... values) {
        return fetch(User.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.iot.baobiao.jooq.tables.pojos.User fetchOneById(Integer value) {
        return fetchOne(User.USER.ID, value);
    }

    /**
     * Fetch records that have <code>phonenum IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.User> fetchByPhonenum(String... values) {
        return fetch(User.USER.PHONENUM, values);
    }

    /**
     * Fetch a unique record that has <code>phonenum = value</code>
     */
    public com.iot.baobiao.jooq.tables.pojos.User fetchOneByPhonenum(String value) {
        return fetchOne(User.USER.PHONENUM, value);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.User> fetchByUsername(String... values) {
        return fetch(User.USER.USERNAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.User> fetchByPassword(String... values) {
        return fetch(User.USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.User> fetchByEmail(String... values) {
        return fetch(User.USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>corporation IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.User> fetchByCorporation(String... values) {
        return fetch(User.USER.CORPORATION, values);
    }

    /**
     * Fetch records that have <code>industry IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.User> fetchByIndustry(Integer... values) {
        return fetch(User.USER.INDUSTRY, values);
    }

    /**
     * Fetch records that have <code>sites IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.User> fetchBySites(String... values) {
        return fetch(User.USER.SITES, values);
    }

    /**
     * Fetch records that have <code>keyword IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.User> fetchByKeyword(String... values) {
        return fetch(User.USER.KEYWORD, values);
    }
}
