/**
 * This class is generated by jOOQ
 */
package com.iot.baobiao.jooq.tables.daos;


import com.iot.baobiao.jooq.tables.UserSite;
import com.iot.baobiao.jooq.tables.records.UserSiteRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserSiteDao extends DAOImpl<UserSiteRecord, com.iot.baobiao.jooq.tables.pojos.UserSite, Integer> {

    /**
     * Create a new UserSiteDao without any configuration
     */
    public UserSiteDao() {
        super(UserSite.USER_SITE, com.iot.baobiao.jooq.tables.pojos.UserSite.class);
    }

    /**
     * Create a new UserSiteDao with an attached configuration
     */
    @Autowired
    public UserSiteDao(Configuration configuration) {
        super(UserSite.USER_SITE, com.iot.baobiao.jooq.tables.pojos.UserSite.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.iot.baobiao.jooq.tables.pojos.UserSite object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.UserSite> fetchById(Integer... values) {
        return fetch(UserSite.USER_SITE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.iot.baobiao.jooq.tables.pojos.UserSite fetchOneById(Integer value) {
        return fetchOne(UserSite.USER_SITE.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.UserSite> fetchByUserId(Integer... values) {
        return fetch(UserSite.USER_SITE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>site_id IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.UserSite> fetchBySiteId(Integer... values) {
        return fetch(UserSite.USER_SITE.SITE_ID, values);
    }

    /**
     * Fetch records that have <code>sitename IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.UserSite> fetchBySitename(String... values) {
        return fetch(UserSite.USER_SITE.SITENAME, values);
    }

    /**
     * Fetch records that have <code>start_url IN (values)</code>
     */
    public List<com.iot.baobiao.jooq.tables.pojos.UserSite> fetchByStartUrl(String... values) {
        return fetch(UserSite.USER_SITE.START_URL, values);
    }
}
